# Generated by Django 5.0.4 on 2024-04-06 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Креслення', 'Креслення'), ('Розрахунок', 'Розрахунок'), ('Граф', 'Граф')], max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diameter', models.DecimalField(decimal_places=2, max_digits=6)),
                ('node1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='heatnet_app.node')),
                ('node2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='heatnet_app.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heatnet_app.project'),
        ),
    ]
