# Generated by Django 5.0.4 on 2024-04-06 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='heatnet_app.project'),
        ),
    ]
