# Generated by Django 5.0.4 on 2024-04-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0002_alter_node_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='node1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='heatnet_app.node'),
        ),
        migrations.AlterField(
            model_name='link',
            name='node2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='heatnet_app.node'),
        ),
    ]
