# Generated by Django 5.0.4 on 2024-04-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0003_alter_link_node1_alter_link_node2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='weight',
            new_name='flow_rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='link',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='diameter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(choices=[('Теплова камера', 'Теплова камера'), ('Споживач', 'Споживач')], max_length=100),
        ),
    ]
