# Generated by Django 5.0.4 on 2024-04-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0005_link_speed_alter_link_flow_rate_alter_link_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='flow_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Витрата (т/год)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Дожина ділянки (м)'),
        ),
        migrations.AlterField(
            model_name='link',
            name='speed',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Швидкість(м/с)'),
        ),
    ]
