# Generated by Django 5.0.4 on 2024-04-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0006_alter_link_flow_rate_alter_link_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='link',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=''),
        ),
    ]
