# Generated by Django 5.0.4 on 2024-04-13 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0007_link_description_link_end_date_link_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='link',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
    ]
