# Generated by Django 5.0.4 on 2024-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heatnet_app', '0009_remove_link_description_remove_node_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='type',
            field=models.CharField(blank=True, choices=[('Теплова камера', 'Теплова камера'), ('Споживач', 'Споживач')], max_length=100, null=True),
        ),
    ]
